import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../../globals.css";
import Sidebar from "@/components/layouts/Sidebar";
import DashboardNavbar from "@/components/layouts/DashboardNavbar";
const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="flex">
          <div className="w-[18%]">
            <Sidebar />
          </div>
          <div className="col-span-3 overflow-auto lg:col-span-5 lg:border-l w-[82%]">
            <div className="px-6 py-6 lg:px-8">
              <DashboardNavbar />
              <div className="pt-6">{children}</div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
